In [1]:
import numpy as np

## DataTypes & Attributes

In [3]:
#Numpy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1


array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]]])

In [8]:
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a1.shape

(3,)

In [11]:
a2.shape

(2, 4)

In [12]:
a3.shape

(2, 3, 3)

In [13]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [15]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
#Create a dataframe from a Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2  3
0  1  2  3  4
1  5  6  7  8

In [18]:
##Creating Arrays

In [19]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [20]:
sample_array.dtype

dtype('int64')

In [22]:
ones = np.ones((2, 3))

In [23]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
ones.dtype

dtype('float64')

In [25]:
type(ones)

numpy.ndarray

In [26]:
zeros = np.zeros((2, 3))

In [27]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [5]:
import numpy as np

In [7]:
random_array = np.random.randint(0, 10, size = (3,5))
random_array

array([[9, 7, 3, 9, 2],
       [4, 0, 5, 7, 0],
       [2, 3, 5, 9, 5]])

In [8]:
np.random.random((5, 3))

array([[0.82897313, 0.00410923, 0.01453022],
       [0.52552442, 0.14933864, 0.6303056 ],
       [0.87150589, 0.04481408, 0.13639624],
       [0.08831952, 0.68629883, 0.89348153],
       [0.20253765, 0.38408331, 0.94031503]])

In [13]:
#Pseudo random numbers
#np.random.seed(seed = 42)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[1, 4, 3],
       [3, 1, 0],
       [9, 4, 7],
       [7, 5, 2],
       [3, 1, 0]])

In [14]:
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.10461874, 0.17019216, 0.46037436],
       [0.78346678, 0.08537915, 0.47633602],
       [0.35297353, 0.20887789, 0.1149501 ],
       [0.56819437, 0.96155176, 0.89577921],
       [0.45740887, 0.43262346, 0.0023977 ]])

## Viewing arrays and matrices

In [15]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 7, 9])

In [27]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

## Manupulating and comparing arrays

In [28]:
a1

array([1, 2, 3])

In [25]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [29]:
a1 + ones

array([2., 3., 4.])

In [30]:
a1 - ones

array([0., 1., 2.])

In [31]:
a1 * ones

array([1., 2., 3.])

In [32]:
a2 = np.array([[1, 2, 3],
               [5, 6, 7]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]]])

In [34]:
a1 * a3

array([[[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]],

       [[10, 22, 36],
        [13, 28, 45],
        [16, 34, 54]]])

In [39]:
a1 / ones

array([1., 2., 3.])

In [41]:
a2 ** 2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [42]:
np.square(a3)

array([[[  1,   4,   9],
        [ 16,  25,  36],
        [ 49,  64,  81]],

       [[100, 121, 144],
        [169, 196, 225],
        [256, 289, 324]]])